import { expect, test } from "@playwright/test";

test("reviewed expansion works with scrolling, inclusive spans and attribution downloads", async ({ page, request }) => {
  await page.clock.setFixedTime(new Date("2026-09-11T17:00:00Z"));
  await page.goto("/");
  const chooser = page.getByRole("dialog", { name: "Follow your sports" });
  await expect(chooser).toBeVisible();
  await expect(chooser.getByText("NFL · selected games", { exact: true })).toBeVisible();
  await expect(chooser.getByText("World Climbing", { exact: true })).toBeVisible();
  await expect(chooser.getByText("Golf · women's majors", { exact: true })).toBeVisible();
  await chooser.getByRole("button", { name: "Clear", exact: true }).click();
  await chooser.getByText("IWF Worlds", { exact: true }).click();
  await chooser.getByRole("button", { name: "Show my calendar" }).click();
  await page.getByPlaceholder("Search events").fill("Weightlifting");
  const result = page.getByRole("region", { name: "Search results" }).getByRole("button");
  await expect(result).toHaveCount(1);
  await result.click();
  const detail = page.getByRole("complementary", { name: "Day events" });
  await expect(detail).toContainText("Time TBD");
  await expect(detail).toContainText("through 2026-11-08");
  await expect(detail.getByRole("link", { name: "Schedule source" })).toHaveAttribute("href", /wikidata\.org.*oldid=2499700131/);
  await page.getByRole("button", { name: "Close day" }).click();
  await page.getByPlaceholder("Search events").fill("");
  await expect(page.locator("#day-2026-10-31 .event-pill")).toHaveCount(1);
  await expect(page.locator("#day-2026-11-01 .event-pill")).toHaveCount(1);
  await page.getByRole("button", { name: "Today", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("September");
  await page.getByRole("button", { name: "About sportsbro and schedule coverage" }).click();
  const about = page.getByRole("dialog", { name: "About sportsbro", exact: true });
  await expect(about).toContainText("19 selected NFL opener, international and holiday games");
  await expect(about).toContainText("CC BY-SA 4.0");
  const download = about.getByRole("link", { name: "Download Wikipedia schedule data" });
  const href = await download.getAttribute("href");
  expect(href).toMatch(/2026-wikipedia-[a-f0-9]{64}\.json$/);
  const response = await request.get(href!);
  expect(response.ok()).toBeTruthy();
  const component = await response.json();
  expect(component.license).toBe("CC BY-SA 4.0");
  expect(component.events.filter((e: { league: string }) => e.league === "NFL")).toHaveLength(19);
});

test("expanded interest labels and date-only card details fit a mobile viewport", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.clock.setFixedTime(new Date("2026-09-11T17:00:00Z"));
  await page.goto("/");
  const chooser = page.getByRole("dialog", { name: "Follow your sports" });
  await expect(chooser).toBeVisible();
  await expect(chooser.getByText("Boxing · selected unifications", { exact: true })).toBeVisible();
  expect(await chooser.evaluate((el) => el.scrollWidth <= el.clientWidth)).toBeTruthy();
  await page.screenshot({ path: "test-results/expansion-mobile.png" });
  await chooser.getByRole("button", { name: "Clear", exact: true }).click();
  await chooser.getByText("Boxing · selected unifications", { exact: true }).click();
  await chooser.getByRole("button", { name: "Show my calendar" }).click();
  await page.getByPlaceholder("Search events").fill("Navarrete");
  await page.getByRole("region", { name: "Search results" }).getByRole("button").click();
  const detail = page.getByRole("complementary", { name: "Day events" });
  await expect(detail).toContainText("three full titles");
  await expect(detail).toContainText("Time TBD");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});
